job.type: train
dataset.name: toy
model: sd_rescal

sd_rescal:
  class_name: SparseDiagonalRescal
  blocks: -1
  block_size: 1
  entity_embedder:
    type: lookup_embedder
    dim: 128  # determine automatically
    dropout: 0.2
  relation_embedder:
    type: lookup_embedder
    dim: -1  # determine automatically
    dropout: 0.2

valid:
  early_stopping:
    patience: 5
  every: 1
  filter_with_test: True
  metric: Accuracy
train:
  optimizer: Adagrad
  optimizer_args:
    lr: 0.1
  batch_size: 128
  max_epochs: 200

eval.type: triple_classification
eval.metrics_per.relation: False

