job:
  device: cuda
  type: train

model: transe

dataset:
  name: fb15k

train:
  batch_size: 256
  loss: margin_ranking
  loss_arg: 0.2
  max_epochs: 200
  optimizer: Adagrad
  optimizer_args:
    lr: 0.01
  type: negative_sampling

negative_sampling:
  num_negatives_o: 3
  num_negatives_p: 0
  num_negatives_s: 3
  sampling_type: uniform

valid:
  early_stopping.patience: 5
  every: 5
  filter_with_test: True
  metric: Accuracy

eval:
  batch_size: 512
  type: triple_classification

transe:
  class_name: TransE
  entity_embedder:
    dim: 100
    initialize: uniform_
    initialize_args:
      uniform_ :
        a: -1.0
    sparse: false
    type: lookup_embedder
    regularize: l2
    regularize_weight: 1.e-05
  relation_embedder:
    dim: 100
    initialize: uniform_
    initialize_args:
      uniform_ :
        a: -1.0
    sparse: false
    type: lookup_embedder
    regularize: l2
    regularize_weight: 1.e-05
  l_norm: 1.
